# Generated by Django 4.2 on 2023-05-22 22:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atp', models.CharField(max_length=50)),
                ('pm_13', models.CharField(max_length=50)),
                ('pm_16', models.CharField(max_length=50)),
                ('pm_18', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id_films', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.classification')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id_gender', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Suscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=128)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.films')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id_likes', models.AutoField(primary_key=True, serialize=False)),
                ('film', models.ManyToManyField(to='administration.films')),
                ('suscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.suscriber')),
            ],
        ),
    ]
