# Generated by Django 4.2 on 2023-05-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='film',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
